# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "CentOS-6.4-x86_64-epel-ansible-v20131227"

  config.vm.provision :shell, :path => "centos6_desktop_install.sh"

  config.vm.provider :virtualbox do |vb|
    config.cache.auto_detect = true # Using https://github.com/fgrehm/vagrant-cachier
  end
end
